export const SUBSECTOR_KPI_HINTS: Record<string, string[]> = {
  // ── Energy & Power ───────────────────────────────────────────────────────────
  "renewable-energy": [
    "Installed capacity (GW) and pipeline under development",
    "Capacity Utilization Factor (CUF %) — proxy for site quality",
    "Levelised Cost of Energy (LCOE ₹/kWh) and tariff realisation",
    "Off-taker mix (DISCOM vs C&I vs PSU) and PPA tenor",
    "Revenue visibility — % revenue under long-term PPAs vs rolling agreements",
    "Project-level leverage (Debt:Equity) and cost of capital",
    "Competitive moat — auction win rate / land bank (utility) vs client retention / O&M stickiness (C&I)",
    "O&M model — in-house vs outsourced; margin and longevity implications",
    "Grid curtailment exposure — interstate corridor congestion risk",
    "Equipment sourcing — China module dependency and BCD/safeguard duty exposure",
    "Storage/BESS and Green Hydrogen integration strategy",
    "Policy sensitivity — RPO compliance risk (utility) vs Open Access policy risk (C&I)",
    "Exit / monetization path — InvIT listing, YieldCo, PE exit, or strategic M&A",
  ],

  "conventional-power-generation": [
    "Plant Load Factor (PLF %) and installed capacity (MW)",
    "Heat rate (kcal/kWh) — operational efficiency benchmark",
    "Fuel cost per unit and sourcing strategy (captive coal vs linkage)",
    "Competitive moat — fuel security, long-term PPAs, or grid-balancing role",
    "Revenue quality — merchant exposure vs regulated/PPA-tied revenue",
    "Forced outage rate — reliability premium in grid balancing",
    "Policy risk — coal allocation policy, RPO mandates, and stranded-asset risk from energy transition",
    "Transition strategy — retrofit for flexibility, co-firing, or managed decline",
    "Net debt / EBITDA and refinancing risk on aging assets",
  ],

  "power-transmission-distribution-grid": [
    "AT&C losses (%) — core efficiency metric",
    "SAIDI / SAIFI — reliability indices regulators track",
    "Revenue gap — subsidy dependence and receivables from DISCOMs",
    "Competitive moat — regulated natural monopoly; differentiation is execution quality",
    "Regulatory framework — CERC/SERC tariff order predictability",
    "Smart metering and digitalisation rollout (%)",
    "Renewable integration capacity — grid flexibility investments",
    "Capex pipeline (₹ cr) and TBCB award pipeline",
    "Policy risk — AT&C loss reduction targets, DISCOM privatisation exposure",
  ],

  "oil-gas": [
    "Reserve replacement ratio — upstream sustainability",
    "Production volumes (boe/day) and growth",
    "Lifting cost ($/boe) and cost quartile position",
    "Gross Refining Margin (GRM $/bbl) — downstream profitability",
    "Upstream vs midstream vs downstream revenue mix",
    "Competitive moat — reserve base, refinery complexity (Nelson Index), pipeline infrastructure",
    "Revenue quality — commodity price exposure vs integrated hedging",
    "Exploration acreage and discovery track record",
    "Policy risk — APM pricing, export restrictions, subsidy burden on LPG/kerosene",
    "Energy transition exposure — portfolio pivot to gas, biofuels, or renewables",
    "Net debt / EBITDA and capex discipline",
  ],

  "energy-storage-green-hydrogen": [
    "GWh storage capacity deployed or contracted",
    "Levelised Cost of Storage (LCOS $/MWh) vs grid parity",
    "Green H₂ production cost ($/kg) vs grey H₂ cost",
    "Electrolyser capacity (MW) and technology choice (PEM vs Alkaline)",
    "Offtake agreements (MW/MTPA) — revenue visibility",
    "Competitive moat — technology IP, electrolyser manufacturing, or project developer scale",
    "Policy dependency — PLI, SIGHT scheme, and national H₂ mission tailwinds",
    "Export market strategy — Middle East, EU, Japan demand pipeline",
    "Capital intensity and project IRR at current cost curve",
    "Strategic archetype — technology provider vs integrated developer vs off-taker",
  ],

  // ── Financial Services ───────────────────────────────────────────────────────
  "banking": [
    "Gross NPA / Net NPA ratio (%) — asset quality",
    "CASA ratio (%) — low-cost funding moat",
    "Net Interest Margin (NIM %) — core earnings power",
    "Credit cost (%) and provision coverage ratio",
    "Capital Adequacy Ratio (CAR %) — regulatory buffer",
    "Return on Assets (ROA %) and Return on Equity (ROE %)",
    "Competitive moat — branch network density, CASA franchise, or digital platform stickiness",
    "Revenue quality — retail vs corporate loan mix; fee income share",
    "Credit cycle positioning — sector concentration and restructured book",
    "Digital adoption — mobile banking MAU, UPI market share, cost-to-serve reduction",
    "Policy sensitivity — PSL compliance, interest rate sensitivity on NIM, RBI regulatory actions",
    "Strategic archetype — universal bank vs retail-focused vs wholesale/corporate specialist",
  ],

  "nbfcs-microfinance": [
    "AUM size and growth (%)",
    "Gross NPA (%) and provision coverage",
    "Cost of funds (%) — funding mix advantage vs banks",
    "Net Interest Margin (NIM %) — spread sustainability",
    "Average ticket size and borrower profile",
    "Collection efficiency (%) — early-warning stress indicator",
    "Competitive moat — last-mile distribution, co-lending relationships, or niche segment lock-in",
    "Funding mix — bank loans vs NCD vs securitisation; ALM risk",
    "Policy risk — MFI lending rate cap, RBI NBFC regulation tightening, priority sector rules",
    "Credit cycle exposure — rural income sensitivity, monsoon dependency",
    "Capital raise track record and promoter quality",
  ],

  "insurance": [
    "Combined ratio (%) — core underwriting profitability",
    "Loss ratio (%) and claims management capability",
    "Expense ratio (%) — distribution cost efficiency",
    "Solvency ratio — regulatory capital buffer",
    "Gross Written Premium (GWP ₹ cr) and growth (%)",
    "Competitive moat — distribution network (tied agents vs bancassurance vs digital), brand trust",
    "Revenue quality — renewal premium share vs new business; persistency ratio",
    "Product mix — protection vs savings vs health; margin profile differences",
    "Policy risk — IRDAI product regulation, commission structure changes, mandatory covers",
    "Strategic archetype — low-cost digital disruptor vs distribution-heavy traditional vs bancassurance-led",
    "Investment income yield on float — AUM quality",
  ],

  "asset-management-capital-markets": [
    "Assets Under Management (AUM ₹ cr) and market share (%)",
    "SIP book size and monthly inflow — retail franchise quality",
    "Average expense ratio (%) — pricing power vs competitive pressure",
    "Fund performance vs benchmark (alpha) — investment capability moat",
    "Retail vs institutional vs HNI AUM mix — revenue stability",
    "Competitive moat — distributor relationships, brand trust, or performance track record",
    "Revenue quality — equity AUM share (higher margin) vs debt/liquid AUM",
    "Policy risk — SEBI TER reduction, direct plan adoption eating into distributor margins",
    "Distribution reach — empanelled distributors and digital direct platform share",
    "Strategic archetype — scale leader vs boutique performance house vs digital-first",
  ],

  "fintech-digital-payments": [
    "Gross Merchandise Value / Total Payment Volume (GMV/TPV ₹ cr)",
    "Take rate (bps) — monetisation efficiency",
    "Monthly Active Users (MAU) and DAU:MAU ratio",
    "Customer Acquisition Cost (CAC ₹) and payback period",
    "Revenue per user (ARPU) and unit economics trajectory",
    "Competitive moat — network effects, UPI market share, merchant lock-in, or data flywheel",
    "Revenue quality — payment processing vs credit vs SaaS; cross-sell penetration",
    "Regulatory licenses held — PA, PPI, NBFC-MFI; compliance moat",
    "Policy risk — MDR caps, RBI data localisation, UPI interchange debate",
    "Strategic archetype — payments infra provider vs consumer super-app vs B2B embedded finance",
    "Path to profitability — burn rate and contribution margin per transaction",
  ],

  // ── Technology & Internet ────────────────────────────────────────────────────
  "it-services-bpm": [
    "Revenue ($ bn) and constant-currency growth (%)",
    "EBITDA margin (%) — operational leverage benchmark",
    "Revenue per employee ($) — productivity proxy",
    "Deal TCV (Total Contract Value) and pipeline — forward revenue visibility",
    "Attrition rate (%) — talent risk and replacement cost",
    "Competitive moat — proprietary platforms, domain IP, or hyperscaler partnership depth",
    "Revenue quality — US vs Europe vs non-linear revenue mix; GenAI / digital share (%)",
    "Client concentration — top 10 clients as % of revenue",
    "Policy risk — US immigration/visa policy, protectionism in key markets",
    "Strategic archetype — scale generalist (TCS/Infosys) vs domain specialist vs product-led",
    "Capital allocation — dividend yield, buyback track record, M&A integration quality",
  ],

  "saas-software-products": [
    "Annual Recurring Revenue (ARR) and growth (%)",
    "Net Revenue Retention (NRR %) — expansion within installed base",
    "Gross churn rate (%) — product stickiness",
    "Customer Acquisition Cost (CAC ₹/$) and LTV:CAC ratio",
    "Gross margin (%) — software economics benchmark",
    "Competitive moat — switching costs, data lock-in, ecosystem integrations, or workflow criticality",
    "Revenue quality — enterprise vs SMB mix; multi-year contract share",
    "Rule of 40 score (growth % + EBITDA margin %)",
    "Policy risk — data localisation, cross-border data flow regulations",
    "Strategic archetype — horizontal platform vs vertical SaaS vs developer tools vs AI-native",
    "Path to profitability — burn multiple and efficiency ratio",
  ],

  "ecommerce-quick-commerce": [
    "Gross Merchandise Value (GMV ₹ cr) and growth (%)",
    "Take rate (%) and contribution margin per order",
    "Dark store / fulfilment centre count and coverage",
    "Average Order Value (AOV) and order frequency",
    "Customer Acquisition Cost (CAC ₹) and repeat rate (%)",
    "Competitive moat — assortment depth, delivery SLA, private label margin, or hyperlocal density",
    "Revenue quality — first-party vs marketplace GMV; advertising revenue share",
    "Unit economics — contribution margin per order trajectory",
    "Policy risk — FDI in e-commerce regulations, inventory model restrictions",
    "Strategic archetype — category-killer (grocery/fashion) vs horizontal marketplace vs ultra-fast specialist",
    "Path to profitability — burn rate and net revenue after discounts",
  ],

  "internet-consumer-tech-platforms": [
    "Monthly / Daily Active Users (MAU/DAU) and DAU:MAU ratio",
    "ARPU (₹) and monetisation rate (%)",
    "Time-on-platform (mins/day) — engagement moat",
    "Customer Acquisition Cost (CAC) and organic vs paid mix",
    "Competitive moat — network effects, content flywheel, creator ecosystem, or social graph",
    "Revenue quality — advertising vs subscription vs transaction; top-of-funnel vs commerce",
    "Policy risk — IT Rules 2021, digital taxation, content regulation, data privacy law",
    "Strategic archetype — social media vs content platform vs super-app vs classifieds/transactions",
    "Path to profitability — contribution margin and EBITDA bridge",
    "International / India-first positioning and global scalability",
  ],

  "telecom": [
    "ARPU (₹/month) and trajectory",
    "Subscriber base (mn) and net adds",
    "Spectrum holdings (MHz per band) — infrastructure moat",
    "Capex/Revenue ratio (%) — 5G investment burden",
    "Monthly churn rate (%) — subscriber stickiness",
    "Competitive moat — spectrum depth, tower infrastructure, or enterprise/B2B franchise",
    "Revenue quality — wireless vs wireline vs enterprise vs content mix",
    "5G rollout coverage (%) and monetisation path (FWA, enterprise slicing)",
    "Policy risk — spectrum auction pricing, AGR dues, interconnect regulation",
    "Strategic archetype — scale leader vs challenger (pricing-led) vs enterprise-focused",
    "Net debt / EBITDA — leverage from 5G capex cycle",
  ],

  // ── Healthcare & Pharma ──────────────────────────────────────────────────────
  "pharmaceuticals": [
    "R&D spend as % of revenue — innovation pipeline investment",
    "ANDA / NDA filings and US generic pipeline depth",
    "API vs formulations revenue mix — integration and margin implications",
    "USFDA / WHO-GMP facility compliance record",
    "Domestic vs export revenue split and geography concentration",
    "Competitive moat — product complexity (injectables/biologics), first-to-file positions, or API backward integration",
    "Revenue quality — branded generics vs commodity generics; specialty / complex product share",
    "Patent cliff exposure vs new product launch cadence",
    "Policy risk — DPCO price controls on domestic market, US FDA import alerts",
    "Strategic archetype — India-centric branded generic vs US generics scale player vs CDMO/API specialist",
    "M&A track record and in-licensing pipeline",
  ],

  "hospitals-healthcare-delivery": [
    "Bed count and occupancy rate (%)",
    "Average Revenue Per Occupied Bed (ARPOB ₹/day)",
    "Payer mix — self-pay vs insurance (cashless) vs government schemes",
    "Average Length of Stay (ALOS days) — clinical efficiency",
    "EBITDA margin (%) — mature vs ramp-up facility mix impact",
    "Competitive moat — clinical brand (super-specialty), doctor stickiness, or insurance empanelment network",
    "Revenue quality — high-complexity surgical mix vs OPD/diagnostics; insurance cashless share",
    "Expansion model — owned vs leased vs O&M management contracts",
    "Policy risk — CGHS/PMJAY pricing controls, clinical establishment regulations",
    "Strategic archetype — premium tertiary (Apollo/Fortis) vs mid-market (Aster) vs government-scheme-led",
    "Greenfield payback period (years) — capital efficiency benchmark",
  ],

  "diagnostics-medical-devices": [
    "Tests per day / Revenue per test (₹)",
    "Owned lab count, collection centre network, and geographic spread",
    "Hub-and-spoke vs franchise vs home collection model",
    "B2B (hospital referral) vs B2C (walk-in) revenue mix",
    "EBITDA margin (%) — asset intensity comparison",
    "Competitive moat — brand trust in accuracy, turnaround time (TAT), or franchise network density",
    "Revenue quality — routine vs specialised / genomics tests; high-margin test mix",
    "Policy risk — NABL accreditation requirements, price regulation on diagnostic packages",
    "Strategic archetype — national branded chain vs regional dominant vs hospital-integrated labs",
    "Digitalisation — app-led bookings, AI-assisted reporting, home collection share (%)",
  ],

  "healthtech-digital-health": [
    "Monthly Active Users (MAU) / Paid subscribers",
    "Patient Acquisition Cost (PAC ₹) and retention rate",
    "ARPU (₹) and revenue per consult",
    "B2C vs B2B2C (insurer/employer/hospital) revenue mix",
    "Competitive moat — doctor network quality, clinical data flywheel, or insurer integrations",
    "Revenue quality — recurring subscription vs transactional consult fees",
    "Regulatory approvals — MDR compliance, CDSCO, ABDM integration",
    "Policy risk — telemedicine regulation, data privacy under DPDP Act, ABDM interoperability mandates",
    "Strategic archetype — telemedicine platform vs diagnostics aggregator vs chronic care manager vs health insurer partner",
    "Unit economics and path to profitability — CAC payback and LTV",
  ],

  // ── Consumer & Retail ────────────────────────────────────────────────────────
  "fmcg": [
    "Revenue and volume growth (%) — separating price vs volume",
    "Gross margin (%) and A&P spend as % of revenue",
    "Direct distribution reach (towns / retail touchpoints)",
    "Market share by category (%) — leadership position moat",
    "Competitive moat — brand equity, distribution depth, or premiumisation ladder",
    "Revenue quality — premium vs mass mix; rural vs urban split and their growth rates",
    "Working capital cycle — trade payables vs receivables; distributor strength",
    "Policy risk — GST rate changes, FDI in retail, agricultural commodity price controls",
    "Strategic archetype — diversified FMCG conglomerate vs focused category leader vs challenger brand",
    "Innovation pipeline — new product launches contributing to incremental revenue (%)",
  ],

  "retail": [
    "Revenue per sq ft (₹) — space productivity",
    "Same-store sales growth (SSSG %) — organic momentum",
    "Inventory days — working capital efficiency",
    "Private label share (%) — margin enhancement lever",
    "Competitive moat — location network, loyalty program stickiness, or private label franchise",
    "Revenue quality — fashion vs grocery vs electronics mix; online penetration (%)",
    "Store economics — capex per store, payback period, and EBITDA per store",
    "Policy risk — FDI in multi-brand retail, e-commerce regulation, zoning restrictions",
    "Strategic archetype — format specialist (value/hypermarket) vs omnichannel leader vs luxury/lifestyle",
    "Omnichannel integration — click-and-collect, inventory-online visibility, app vs store footfall",
  ],

  "consumer-durables-electronics": [
    "Market share by category (%) — volume and value",
    "Revenue growth (%) and gross margin (%)",
    "Distribution network — dealer/retailer count and exclusive reach",
    "After-sales service network — serviceability as a moat",
    "Competitive moat — brand positioning, energy rating leadership, or channel exclusivity",
    "Revenue quality — premium vs mass segment mix; B2B/institutional vs retail",
    "Import dependency — China sourcing exposure and PLI localisation benefit",
    "Policy risk — BIS standards, energy efficiency mandates, anti-dumping duties on imports",
    "Strategic archetype — Indian incumbent (Voltas/Havells) vs MNC brand vs value disruptor",
    "Innovation cadence — smart/IoT product share; R&D spend (%)",
  ],

  "apparel-textiles-footwear": [
    "Revenue and EBITDA margin (%)",
    "Capacity utilisation (%) and value-added product mix",
    "Export revenue share and destination concentration",
    "Brand vs private label / B2B revenue mix",
    "Competitive moat — design/speed-to-market (fashion), cost leadership (commodities), or customer captivity (technical textiles)",
    "Revenue quality — long-term supply agreements vs spot; high-margin finished goods vs yarn/fabric",
    "China+1 / FTA tailwind — order diversion from Bangladesh or China",
    "Policy risk — import duty on synthetic fibre, export incentive (RoDTEP) changes, labour regulations",
    "Strategic archetype — commodity exporter vs branded apparel vs technical/performance fabrics vs fast fashion",
    "PLI benefit accrual (₹ cr) and eligibility",
  ],

  "food-beverage-qsr": [
    "Same-store sales growth (SSSG %) — brand health indicator",
    "Average Daily Sales per store (ADS ₹) and store count",
    "Payback period per new store (years) — capital efficiency",
    "Gross margin (%) and raw material cost as % of revenue",
    "Delivery vs dine-in revenue mix and margin differential",
    "Competitive moat — brand recall, supply chain integration, menu innovation, or real estate network",
    "Revenue quality — company-owned vs franchised vs sub-franchised store economics",
    "Policy risk — FSSAI regulations, GST on delivery, zomato-swiggy platform dependency",
    "Strategic archetype — value QSR vs premium casual dining vs delivery-first dark kitchen vs café",
    "Franchise model health — franchisee profitability and churn rate",
  ],

  // ── Automotive & Industrial Manufacturing ────────────────────────────────────
  "automotive-oems": [
    "Domestic market share by segment — PV, CV, 2W/3W (%)",
    "EV volume share (%) and transition roadmap",
    "EBITDA margin (%) — commodity cost and mix effects",
    "Localisation level (%) — import dependency and PLI eligibility",
    "Dealer network size and satisfaction — last-mile moat",
    "Competitive moat — brand positioning, model cycle freshness, or powertrain technology",
    "Revenue quality — product mix (SUV vs entry vs LCV vs M&HCV); export share",
    "EV transition risk — ICE asset stranding vs EV investment ramp",
    "Policy risk — CAFE norms, scrappage policy, EV subsidy (FAME) dependency, import duty structure",
    "Strategic archetype — volume leader vs premium aspirant vs EV-first disruptor vs export-oriented",
  ],

  "auto-components": [
    "Revenue and EBITDA margin (%)",
    "Customer concentration — top 3 OEM share of revenue",
    "OEM vs aftermarket vs export revenue mix",
    "EV-agnostic revenue share (%) — transition resilience",
    "Capacity utilisation (%) and working capital cycle",
    "Competitive moat — sole-source supply agreements, precision manufacturing capability, or global OEM certification",
    "Revenue quality — proprietary product vs sub-contract assembly; EV content per vehicle",
    "Policy risk — PLI eligibility, BIS standards, CAFE norm changes affecting OEM mix",
    "Strategic archetype — safety-critical tier-1 vs commoditised tier-2 vs EV-native new entrant",
    "EV transition opportunity — new components (battery pack, e-axle) vs risk (ICE parts obsolescence)",
  ],

  "electric-vehicles-battery": [
    "Vehicle range (km) per charge and real-world performance",
    "Battery cost ($/kWh) vs ICE total cost of ownership crossover",
    "Domestic market share by segment (%)",
    "Order book and delivery backlog",
    "Localisation level (%) and PLI / FAME subsidy dependency",
    "Competitive moat — battery technology IP, charging network, or OEM partnership",
    "Revenue quality — direct sales vs dealer; fleet / B2B vs retail mix",
    "Charging infrastructure — proprietary network vs third-party reliance",
    "Policy risk — FAME phase-out, PLI eligibility criteria, import duty on cells",
    "Strategic archetype — vertically integrated (battery + vehicle) vs assembler vs fleet specialist",
  ],

  "industrial-manufacturing-capital-goods": [
    "Order book / revenue ratio — forward visibility",
    "Order inflow growth (%) and pipeline quality",
    "EBITDA margin (%) and working capital cycle (days)",
    "Export share (%) and international order pipeline",
    "Competitive moat — proprietary technology, long-cycle relationships, or after-sales service lock-in",
    "Revenue quality — government vs private capex mix; one-time equipment vs recurring O&M revenue",
    "Policy risk — capex cycle dependency on government infra spend, PLI eligibility",
    "Strategic archetype — defence/railways/energy specialist vs general industrial vs EPC-led",
    "China import substitution opportunity — products at risk vs products with domestic advantage",
  ],

  "electronics-semiconductors": [
    "PLI benefit accrual (₹ cr) and qualifying investments",
    "Domestic vs export revenue mix",
    "Import substitution achieved (%) — localisation progress",
    "Capex (₹ cr) deployed and capacity ramp timeline",
    "Technology node / capability — assembly vs OSAT vs fabrication",
    "Competitive moat — customer qualifications, quality certifications, or IP portfolio",
    "Revenue quality — consumer electronics vs industrial vs defense mix; design-linked vs contract manufacturing",
    "Policy risk — PLI scheme continuity, geopolitical supply chain shifts, US export controls on chips",
    "Strategic archetype — contract assembler (EMS) vs OSAT packaging vs design house vs wafer fab",
    "Global supply chain positioning — China+1 beneficiary vs Taiwan concentration risk",
  ],

  // ── Infrastructure, Real Estate & Construction ────────────────────────────────
  "real-estate": [
    "Pre-sales value (₹ cr) and units — top-line visibility",
    "Collections (₹ cr) — cash conversion quality",
    "Inventory overhang (months of sales) — demand health",
    "Net debt / equity — leverage and execution risk",
    "Competitive moat — brand trust for delivery, land bank in premium micro-markets, or repeat buyer rate",
    "Revenue quality — residential vs commercial vs plotted development; affordable vs luxury mix",
    "Launch pipeline (mn sq ft) and land acquisition strategy",
    "Policy risk — RERA compliance, stamp duty changes, interest rate sensitivity on affordability",
    "Strategic archetype — branded luxury developer vs affordable housing specialist vs commercial-office REIT-play",
    "REITable asset quality — leasable commercial area and occupancy for monetisation",
  ],

  "construction-engineering-epc": [
    "Order book / revenue ratio — execution backlog",
    "Order inflow growth (%) and sector mix",
    "EBITDA margin (%) — bid discipline and cost overrun risk",
    "Working capital cycle (days) — government payment risk",
    "Project concentration — top 3 orders as % of book",
    "Competitive moat — domain expertise (marine, tunnelling, nuclear), execution track record, or prequalification certifications",
    "Revenue quality — government vs private; fixed-price vs cost-plus contract mix",
    "Policy risk — NHAI/NHIDCL award pace, government payment delays, input cost escalation clauses",
    "International order share (%) — currency and geopolitical diversification",
    "Strategic archetype — domestic infra pure-play vs diversified EPC vs international specialist",
  ],

  "cement": [
    "Installed capacity (MTPA) and utilisation (%)",
    "EBITDA per tonne (₹) — core profitability benchmark",
    "Cost of production per tonne (₹) — efficiency benchmark",
    "Freight cost per tonne — logistics network advantage",
    "Competitive moat — regional market dominance, captive power / fuel, or logistics infrastructure",
    "Revenue quality — trade vs non-trade mix; premium product share (%)",
    "Fuel cost exposure — pet coke vs coal vs AFR mix; WHR capacity",
    "Policy risk — fuel import duties, housing / infra government spend cycle",
    "Strategic archetype — pan-India scale leader vs regional champion vs niche premium player",
    "Capacity expansion pipeline (MTPA) and greenfield vs brownfield cost",
  ],

  "roads-highways-urban-infrastructure": [
    "Order book / revenue ratio and NHAI award pipeline",
    "HAM vs BOT vs EPC project mix — risk and return profile",
    "Toll collection (₹ cr/km) and traffic growth",
    "Equity IRR on BOT/HAM projects (%) — capital allocation quality",
    "Collection efficiency (%) and dispute track record",
    "Competitive moat — prequalification for large bids, balance sheet for BOT equity, or DFC/metro specialist",
    "Revenue quality — annuity (HAM) vs traffic-linked (BOT) vs construction (EPC) mix",
    "Policy risk — government payment timelines on HAM, land acquisition delays, arbitration outcome risk",
    "Strategic archetype — pure EPC contractor vs BOT/HAM developer vs urban metro/transit specialist",
    "Net debt / equity — leveraged developer vs asset-light contractor",
  ],

  "ports-airports-logistics-infrastructure": [
    "Cargo throughput (MTPA / mn passengers)",
    "EBITDA per tonne / per passenger (₹)",
    "Capacity utilisation (%) and expansion timeline",
    "Concession tenure remaining (years) — asset life",
    "Competitive moat — captive hinterland, rail/road connectivity, or multi-modal integration",
    "Revenue quality — cargo mix (container vs bulk vs liquid); aero vs non-aero revenue at airports",
    "Commodity concentration risk — port dependence on single commodity",
    "Policy risk — tariff authority (TAMP/AERA) regulation, concession renewal risk",
    "Strategic archetype — bulk commodity port vs container terminal vs multi-modal logistics hub vs greenfield airport",
    "Privatisation / monetisation angle — REIT, InvIT, or asset sale optionality",
  ],

  // ── Metals, Mining & Chemicals ───────────────────────────────────────────────
  "steel": [
    "Crude steel capacity (MTPA) and utilisation (%)",
    "EBITDA per tonne (₹) — core profitability",
    "Cost of production per tonne (₹) and cost quartile position",
    "Flat vs long product mix — value-add differentiation",
    "Coking coal sourcing — captive mines vs spot import dependency",
    "Competitive moat — captive iron ore / coal, integrated value chain, or downstream finishing",
    "Revenue quality — export share and realisation vs domestic; value-added product mix",
    "Commodity cycle positioning — spot spread vs contracted; inventory strategy",
    "Policy risk — safeguard / anti-dumping duties, iron ore export levy, minimum import price",
    "Strategic archetype — low-cost integrated producer vs niche high-value steel vs downstream fabricator",
    "Debt / EBITDA and capex discipline across the steel cycle",
  ],

  "non-ferrous-metals": [
    "Production volume (MT) and capacity",
    "Cost quartile position globally (C1 cost $/tonne)",
    "LME price realisation and hedging policy",
    "Integration level — mining → smelting → downstream conversion",
    "Captive mining share (%) — raw material security moat",
    "Competitive moat — lowest-cost position, captive resources, or specialty alloy capability",
    "Revenue quality — commodity ingot vs value-added products (foils, rods, alloys) mix",
    "Commodity cycle sensitivity — beta to LME prices and power cost",
    "Policy risk — bauxite / ore export restrictions, power cost and captive plant policy",
    "Strategic archetype — low-cost commodity producer vs value-added downstream specialist vs recycler",
  ],

  "mining-coal": [
    "Production volume (MT) and growth (%)",
    "E-auction premium over CIL notified price (%)",
    "Cost of production per tonne (₹) and mine life (years)",
    "Captive mine vs CIL-linkage revenue mix",
    "Competitive moat — mine quality (GCV of coal), captive power advantage, or logistics infrastructure",
    "Revenue quality — regulated linkage vs merchant / e-auction premium mix",
    "Washery / beneficiation capacity — value-add margin",
    "Policy risk — coal block allocation, CIL price revision, RPO mandates reducing coal demand long-term",
    "Energy transition exposure — thermal coal demand plateau and managed decline scenario",
    "Strategic archetype — captive block operator vs merchant miner vs coal logistics specialist",
  ],

  "chemicals-petrochemicals": [
    "Revenue and EBITDA margin (%)",
    "Value-added specialty vs commodity product mix",
    "Feedstock integration level — upstream crude / naphtha to downstream chemicals",
    "Export share and key geographies",
    "Capacity utilisation (%) and capex pipeline",
    "Competitive moat — feedstock security, technology licensing, or customer qualification",
    "Revenue quality — long-term offtake agreements vs spot; specialty chemicals margin premium",
    "Commodity spread sensitivity — ethylene/propylene margin volatility",
    "Policy risk — anti-dumping duties on imports, feedstock import dependency",
    "Strategic archetype — bulk commodity chemicals vs specialty chemical differentiated player vs CRAMS feedstock",
  ],

  "specialty-chemicals-agrochemicals": [
    "Revenue growth and gross margin (%)",
    "R&D spend as % of revenue — innovation moat",
    "CRAMS / CDMO revenue share (%) — sticky B2B revenue",
    "China+1 opportunity exposure — products where India has cost/regulatory advantage",
    "Customer concentration — top 3-5 global clients as % of revenue",
    "Competitive moat — complex chemistry capability, regulatory approvals (EPA/REACH), or scale in niche molecules",
    "Revenue quality — proprietary molecules vs toll manufacturing vs generic agrochemicals",
    "Export vs domestic revenue mix and currency diversification",
    "Policy risk — pesticide regulation changes, EPA/EU re-registration risk for key molecules",
    "Strategic archetype — global CRAMS partner vs domestic agrochemical formulator vs specialty chemical innovator",
  ],

  // ── Agriculture & Allied ─────────────────────────────────────────────────────
  "agriculture-farm-inputs": [
    "Market share by crop segment (%) — competitive position",
    "Direct reach — districts and retail touchpoints covered",
    "Product mix — seeds vs pesticides vs micronutrients vs biologicals",
    "R&D pipeline — new variety registrations and molecule launches",
    "Competitive moat — brand trust with farmer, distribution depth, or proprietary seed genetics",
    "Revenue quality — branded / patented products vs generics; recurring vs seasonal",
    "Monsoon and kharif/rabi season dependency",
    "Policy risk — MRP regulation on fertilisers, import duty on agrochemicals, seed price controls",
    "Strategic archetype — seed genetics specialist vs broad-spectrum agrochemical vs input ecosystem aggregator",
    "Digital / agritech integration — advisory services as retention tool",
  ],

  "agritech": [
    "Registered farmer base and monthly active farmers",
    "GMV / transaction value (₹ cr) on platform",
    "Take rate (%) and net revenue",
    "FPO / cooperative partnerships — institutional distribution moat",
    "Geographic coverage (districts / states)",
    "Competitive moat — data on farms (soil, weather, yield), buyer-side aggregation, or input credit",
    "Revenue quality — marketplace commissions vs input retail vs financial services vs SaaS to agri-businesses",
    "Unit economics — CAC per farmer and LTV trajectory",
    "Policy risk — APMC reform rollback risk, eNAM integration, FPO support policy",
    "Strategic archetype — output marketplace vs input distributor vs farm advisory vs agri-fintech",
  ],

  "food-processing": [
    "Revenue and EBITDA margin (%)",
    "Value-add level — raw commodity vs semi-processed vs branded finished goods",
    "Private label vs branded revenue mix",
    "Export share and key geographies",
    "Capacity utilisation (%) and capex pipeline",
    "Competitive moat — backward integration to raw material, brand equity, or retail distribution",
    "Revenue quality — long-term supply agreements vs spot; export vs domestic margin differential",
    "Raw material cost volatility — hedging strategy and pass-through ability",
    "Policy risk — FSSAI regulations, export restrictions on agri commodities, GST on processed foods",
    "Strategic archetype — commodity processor vs branded consumer foods vs B2B ingredient supplier vs export-focused",
  ],

  "fertilizers": [
    "Capacity (MTPA) — urea vs DAP/NPK complex",
    "Cost of production vs MRP / NBS-fixed price",
    "Gas sourcing cost ($/mmBtu) — key input cost variable",
    "Subsidy receivable and working capital cycle",
    "Urea vs complex fertilisers mix — subsidy risk differential",
    "Competitive moat — gas supply security (RLNG vs APM allocation), coastal location, or captive power",
    "Revenue quality — subsidy-linked (urea) vs market-linked (NPK/NBS) mix",
    "Policy risk — gas price policy (APM vs RLNG), urea MRP freeze, subsidy disbursement delays",
    "Strategic archetype — urea incumbent vs complex fertiliser specialist vs new-age bio-fertiliser challenger",
    "Capex pipeline — capacity expansion and energy efficiency upgrades",
  ],

  "dairy-animal-husbandry": [
    "Milk procurement (Lakh Litres Per Day — LLPD) and farmer base",
    "Value-added products (VAP) share of revenue (%) — cheese, paneer, ice cream, whey",
    "EBITDA margin (%) — liquid milk vs VAP margin differential",
    "Geographic reach (states / districts)",
    "Competitive moat — farmer loyalty (procurement price premium), cold chain depth, or brand in VAP",
    "Revenue quality — liquid milk (low margin, high volume) vs VAP (high margin, branded) mix",
    "Cold chain infrastructure — chilling centres, refrigerated transport",
    "Policy risk — milk procurement price (farmer intervention), export policy on SMP/butter",
    "Strategic archetype — cooperative federation (AMUL model) vs private branded dairy vs B2B ingredient supplier",
    "Capacity expansion — processing plant and VAP line investments",
  ],

  // ── Transportation & Logistics ────────────────────────────────────────────────
  "aviation": [
    "Revenue per Available Seat Km (RASK) vs Cost per ASK (CASK) — unit economics spread",
    "Passenger Load Factor (PLF %) — demand utilisation",
    "Fleet size, average age, and fuel efficiency",
    "Domestic vs international route mix and market share",
    "On-time performance (OTP %) — operational quality moat",
    "Competitive moat — slot holdings at congested airports, loyalty program, or low-cost structural advantage",
    "Revenue quality — passenger ancillary vs cargo vs charter mix; corporate vs leisure passenger split",
    "Fuel cost as % of operating cost — hedging policy and currency exposure",
    "Policy risk — ATF pricing, airport slot allocation, bilateral air services agreements",
    "Strategic archetype — low-cost carrier vs full-service network carrier vs regional feeder vs cargo specialist",
    "Net debt / equity — balance sheet resilience through demand cycles",
  ],

  "railways": [
    "Freight volume (Net Tonne Tonne Km — NTTKM) and growth (%)",
    "Revenue per tonne-km (₹) and realisation vs road competition",
    "Commodity mix — coal vs container vs automobile vs bulk",
    "Dedicated Freight Corridor (DFC) exposure — speed and cost advantage",
    "Competitive moat — natural monopoly on high-volume corridors; scale economies on fixed-cost infrastructure",
    "Revenue quality — regulated freight vs commercial / special train revenue",
    "Wagon and locomotive turnaround time — operational efficiency",
    "Policy risk — freight tariff revision, cross-subsidy passenger burden, private train entry",
    "Capex / modernisation plan — station redevelopment, Vande Bharat, electrification",
    "Strategic archetype — core freight corridor vs passenger premium vs private wagons / multimodal operator",
  ],

  "shipping-ports": [
    "Fleet Deadweight Tonnage (DWT) and vessel count",
    "Vessel utilisation rate (%) and time-charter equivalent (TCE) day rate ($)",
    "Time charter vs spot charter revenue mix — earnings stability",
    "Route / trade lane concentration risk",
    "Fleet age profile and newbuild vs secondhand strategy",
    "Competitive moat — modern fuel-efficient fleet (scrubber/LNG), long-term charter contracts, or niche vessel type",
    "Revenue quality — long-term CoA vs spot; product tanker vs bulk vs container mix",
    "Commodity / trade route sensitivity — iron ore, coal, crude routes",
    "Policy risk — IMO decarbonisation regulations (CII, EEXI), Suez/Panama Canal disruption",
    "Strategic archetype — large bulk carrier vs product tanker vs container feeder vs specialised (LNG/chemical)",
  ],

  "road-logistics-3pl": [
    "Fleet size and asset utilisation (%)",
    "Revenue per truck per day (₹) — productivity benchmark",
    "FTL vs LTL vs express vs cold chain revenue mix",
    "Geographic coverage — branch count and pin codes served",
    "EBITDA margin (%) — asset-heavy vs asset-light comparison",
    "Competitive moat — network density, real-time tracking tech, or sector-specific expertise (pharma cold chain)",
    "Revenue quality — long-term contracts vs spot market; key customer concentration",
    "Tech platform capability — TMS, WMS, and live visibility as stickiness tools",
    "Policy risk — GST e-way bill compliance, axle load norms, EV transition cost for fleet",
    "Strategic archetype — asset-heavy full-truckload vs asset-light freight broker vs tech-first platform vs niche cold chain",
  ],

  "warehousing-supply-chain-tech": [
    "Sq ft under management (mn sq ft) and growth",
    "Average rental yield (₹/sq ft/month) and occupancy rate (%)",
    "Grade A vs Grade B warehouse mix — quality and rent premium",
    "E-commerce client share of revenue (%) — demand driver",
    "Geographic spread — Tier-1 vs Tier-2 logistics clusters",
    "Competitive moat — Grade A supply scarcity, proximity to consumption clusters, or WMS/TMS tech platform",
    "Revenue quality — long-term lease vs short-term flex; built-to-suit vs speculative development",
    "EBITDA margin (%) — owned vs managed vs leased model economics",
    "Policy risk — industrial land availability, zoning regulations, GST impact on warehousing consolidation",
    "Strategic archetype — speculative Grade A developer vs built-to-suit specialist vs 3PL-integrated warehousing vs REIT-ready portfolio",
  ],

  // ── Media, Entertainment & Gaming ────────────────────────────────────────────
  "television-film": [
    "Viewership share / GRP — audience moat",
    "Subscription revenue share (%) — stickiness vs ad dependency",
    "Content cost per hour produced (₹ cr) — investment in IP",
    "Ad revenue growth (%) and CPM realisation",
    "OTT / streaming transition — subscriber count and digital revenue share",
    "Competitive moat — library IP ownership, star talent relationships, or genre dominance (GEC/news/sports)",
    "Revenue quality — sports rights (high value, cyclical) vs fiction (recurring) vs news (ad-dependent)",
    "Policy risk — TRP measurement regulation, FDI in broadcasting, content censorship rules",
    "Strategic archetype — linear TV incumbent vs integrated studio+streaming vs content IP monetiser vs pure OTT",
    "Consolidation / M&A angle — streaming bundle aggregation and studio deal activity",
  ],

  "digital-media-ott": [
    "Monthly Active Users (MAU) and paid subscriber base",
    "ARPU (₹/month) and subscriber mix (paid vs free/ad-supported)",
    "Content spend (₹ cr/year) and originals output efficiency",
    "Monthly churn rate (%) — content calendar dependency",
    "Ad vs subscription revenue mix — AVOD vs SVOD economics",
    "Competitive moat — exclusive content / sports rights, language depth, or ecosystem bundling (telco/device)",
    "Revenue quality — India vs international; sports rights spike vs steady drama library",
    "Policy risk — OTT content regulation (IT Rules 2021), content certification, data localisation",
    "Strategic archetype — global-in-India (Netflix/Prime) vs domestic champion (JioCinema/ZEE5) vs niche language/genre",
    "Bundling angle — telco-OTT deal economics and subscriber acquisition cost",
  ],

  "gaming-esports": [
    "Daily Active Users (DAU) and D7/D30 retention rate (%)",
    "ARPU (₹) and pay-to-play conversion rate (%)",
    "Genre concentration — mobile casual vs mid-core vs PC/console",
    "India vs export revenue mix — monetisation gap between markets",
    "Competitive moat — IP ownership, social/clan features, creator ecosystem, or esports franchise value",
    "Revenue quality — in-app purchase vs advertising vs esports prize pool / sponsorship",
    "User Acquisition Cost (UAC) and organic vs paid installs",
    "Policy risk — online gaming tax (28% GST on deposits), DPDP Act on minors' data, game of skill vs chance classification",
    "Strategic archetype — casual hypercasual publisher vs mid-core RPG/strategy vs real-money gaming (RMG) vs esports organiser",
    "International publishing and IP licensing opportunities",
  ],

  "advertising-adtech": [
    "Revenue and market share (%) by medium — digital vs TV vs print vs outdoor",
    "Digital revenue share (%) and programmatic buying adoption",
    "Client retention rate (%) and wallet share with top clients",
    "EBITDA margin (%) and revenue per employee",
    "Competitive moat — proprietary data / DMP, creative IP, media buying clout, or tech platform",
    "Revenue quality — performance-linked vs brand advertising; retainer vs project-based",
    "Macro sensitivity — GDP growth, FMCG/auto ad spend correlation",
    "Policy risk — data privacy (DPDP Act), cookies deprecation, digital ad taxation",
    "Strategic archetype — creative agency vs media buying network vs programmatic adtech vs influencer marketing platform",
    "AI/automation impact — creative automation risk vs data-led targeting opportunity",
  ],

  // ── Education & Skilling ─────────────────────────────────────────────────────
  "k12-education": [
    "Student enrolment and annual fee per student (₹)",
    "Teacher:student ratio and faculty qualification (%PhD or B.Ed)",
    "Board exam performance — pass rate and top scores vs peer schools",
    "Competitive moat — board affiliation (IB/IGCSE/CBSE), brand in premium catchment, or franchise network density",
    "Revenue quality — owned vs franchised school economics; residential vs day school mix",
    "School count and greenfield / acquisition pipeline",
    "Policy risk — NEP 2020 curriculum changes, RTE compliance costs, state fee regulation",
    "Strategic archetype — premium urban chain vs affordable private vs government-partnership model",
    "EBITDA margin (%) — mature school cohort vs ramp-up drag",
    "Exit / consolidation angle — EdTech buyout appetite or REIT-able school property portfolio",
  ],

  "higher-education": [
    "Student enrolment and annual fee per student (₹)",
    "NAAC / NBA / NIRF accreditation and ranking",
    "Campus placement rate (%) and median salary package (₹ LPA)",
    "Faculty:student ratio and PhD-qualified faculty (%)",
    "Research output — publications, patents, and industry-sponsored projects",
    "Competitive moat — brand recognition for placements, industry tie-ups, or international accreditation",
    "Revenue quality — professional (MBA/engineering/medical) vs liberal arts mix; international student share",
    "Regulatory risk — UGC / AICTE fee caps, seat intake controls, deemed university status risks",
    "Strategic archetype — premium deemed university vs public-private partnership vs online/distance learning",
    "Online / hybrid transition and digital revenue share (%)",
  ],

  "edtech": [
    "Monthly Active Users (MAU) and paid conversion rate (%)",
    "Annual Revenue Run Rate (ARR) and growth",
    "ARPU (₹) per learner per year",
    "Course completion rate (%) — learning outcome proxy",
    "Customer Acquisition Cost (CAC ₹) and LTV:CAC ratio",
    "Competitive moat — curriculum depth, live teaching quality, employer recognition, or vernacular reach",
    "Revenue quality — B2C self-paced vs live cohort vs B2B (school/enterprise) mix",
    "Refund rate (%) and consumer protection risk",
    "Policy risk — DPDP Act on student data, UGC online degree regulation, consumer court judgements",
    "Strategic archetype — test-prep focused vs upskilling/professional vs K-12 tuition vs enterprise L&D",
    "Path to profitability — burn multiple and cash runway",
  ],

  "vocational-training-skilling": [
    "Annual training capacity (seats) and actual throughput",
    "Placement rate after training (%) and average salary (₹)",
    "Industry / employer partnership count — job guarantee credibility",
    "Government scheme revenue share — PMKVY, NAPS, etc. (%)",
    "Course portfolio breadth — trades and sectors covered",
    "Competitive moat — employer partnerships, certification recognition (NSDC), or trade-specific lab infrastructure",
    "Revenue quality — government-contracted vs fee-paying private learners; recurring govt contracts vs one-time",
    "Policy risk — PMKVY scheme design changes, fund disbursement delays, new NPS framework",
    "Strategic archetype — government scheme aggregator vs private sector demand-linked trainer vs apprenticeship platform",
    "Digital delivery integration — hybrid model reducing cost per seat",
  ],

  // ── Hospitality & Travel ─────────────────────────────────────────────────────
  "hotels-resorts": [
    "Revenue Per Available Room (RevPAR ₹) — core efficiency metric",
    "Average Daily Rate (ADR ₹) and occupancy rate (%)",
    "Owned vs managed vs franchised property mix — asset-light transition",
    "Brand tier spread — luxury vs upper-upscale vs midscale vs budget portfolio",
    "Competitive moat — brand equity in MICE/weddings, loyalty programme membership, or location monopoly",
    "Revenue quality — F&B and ancillary vs room revenue; leisure vs corporate vs MICE mix",
    "New room pipeline — managed and franchised inventory growth (asset-light vs capex-heavy)",
    "Policy risk — GST on hotel room tariffs (₹7,500 threshold), FHRAI regulations",
    "Strategic archetype — luxury palace hotels vs business hotel chain vs asset-light management company vs budget aggregator",
    "REIT / asset monetisation angle — owned real estate value vs management fee business valuation",
  ],

  "travel-tourism-otas": [
    "Gross Merchandise Value (GMV ₹ cr) and growth (%)",
    "Take rate (%) — monetisation efficiency",
    "Hotels vs flights vs holidays vs bus/rail mix — margin profile",
    "Mobile booking share (%) — app engagement moat",
    "Loyalty programme membership and repeat booking rate (%)",
    "Competitive moat — inventory depth (GDS access, hotel contracts), price comparison leadership, or B2B (corporate travel)",
    "Revenue quality — high-margin holidays / hotels vs low-margin flights; B2B vs B2C mix",
    "Customer Acquisition Cost (CAC ₹) and payback period",
    "Policy risk — DGCA fare caps on flights, package holiday regulation, GST on OTA commissions",
    "Strategic archetype — flights-led OTA vs hotels-focused vs experience/holidays specialist vs B2B corporate travel",
  ],

  // ── Public Sector, Government & Defense ──────────────────────────────────────
  "defense-aerospace": [
    "Order book / revenue ratio — multi-year visibility",
    "Export order share (%) — international competitiveness",
    "Indigenisation level (%) and IDDM / Make in India category",
    "Technology category — platforms (aircraft, ships) vs subsystems vs MRO / services",
    "Government vs commercial revenue mix",
    "Competitive moat — sole-source government designation, JV with foreign OEMs, or unique platform certification",
    "Revenue quality — long-cycle defence contracts vs short-cycle spares/MRO; cost-plus vs fixed-price",
    "Policy risk — defence budget allocation, DPP policy changes, offset obligation compliance",
    "Strategic archetype — HAL/BEL incumbent vs private sector challenger vs niche defence electronics vs space/drone",
    "R&D spend and DRDO partnership depth — technology self-reliance trajectory",
  ],

  "government-psu-enterprises": [
    "Return on Equity (ROE %) vs cost of equity — value creation test",
    "Dividend payout ratio (%) — capital return to government",
    "Capex / revenue ratio (%) — reinvestment efficiency",
    "Market share in regulated sector (%)",
    "Subsidy / government support dependence — pricing freedom",
    "Competitive moat — natural monopoly, government mandate, or scale in capital-intensive sector",
    "Revenue quality — regulated tariff vs market-based pricing; subsidy-linked vs commercial revenue",
    "Policy risk — divestment / privatisation overhang, regulatory tariff revision, PSL / social obligation mandate",
    "Strategic archetype — natural monopoly utility vs strategic sector PSU vs commercially autonomous Navratna",
    "Asset monetisation pipeline — Monetisation Plan (NMP) assets and InvIT/REIT potential",
  ],

  "space-satellite": [
    "Launch success rate (%) and launch cadence (per year)",
    "Satellite manufacturing backlog and on-orbit fleet size",
    "Commercial revenue share (%) — beyond ISRO government mandates",
    "Technology tier — launch vehicles (PSLV/GSLV/LVM3/Reusable) vs satellite bus vs payload",
    "Foreign customer and export order share (%)",
    "Competitive moat — launch cost ($/kg to LEO) vs SpaceX/Arianespace, satellite bus heritage, or frequency spectrum holdings",
    "Revenue quality — government/ISRO contracts vs commercial satellite launch vs data services vs ground segment",
    "Capex and programme timeline — satellite constellation build-out and reusability investment",
    "Policy risk — IN-SPACe licensing framework, frequency allocation, FDI rules in space sector",
    "Strategic archetype — launch vehicle provider vs satellite manufacturer vs earth observation data company vs satellite internet (LEO constellation)",
  ],
};
