export const SUBSECTOR_KPI_HINTS: Record<string, string[]> = {
  // Energy & Power
  "renewable-energy": [
    "Installed capacity (MW/GW)",
    "Capacity Utilization Factor (CUF %)",
    "Levelised Cost of Energy (LCOE ₹/kWh)",
    "Tariff (₹/kWh) and PPA tenor",
    "Off-taker mix (DISCOM vs C&I vs PSU)",
    "Pipeline (MW under development)",
    "Storage/BESS integration",
    "Debt:equity at project level",
  ],
  "conventional-power-generation": [
    "Plant Load Factor (PLF %)",
    "Heat rate (kcal/kWh)",
    "Fuel cost per unit generated",
    "Installed capacity (MW)",
    "Outage frequency & forced outage rate",
    "T&D losses",
    "Fuel sourcing strategy (captive coal vs linkage)",
  ],
  "power-transmission-distribution-grid": [
    "AT&C losses (%)",
    "SAIDI / SAIFI (reliability indices)",
    "Capex per km of line",
    "Smart metering rollout (%)",
    "Revenue gap / subsidy dependence",
    "Renewable integration capacity",
  ],
  "oil-gas": [
    "Reserve replacement ratio",
    "Production volumes (boe/day)",
    "Lifting cost ($/boe)",
    "Refining margins (GRM)",
    "Upstream vs downstream revenue mix",
    "Exploration acreage",
    "Net debt / EBITDA",
  ],
  "energy-storage-green-hydrogen": [
    "GWh storage capacity deployed",
    "Levelised Cost of Storage (LCOS $/MWh)",
    "Electrolyser capacity (MW)",
    "Green H₂ production cost ($/kg)",
    "Offtake agreements (MW / MTPA)",
    "Technology partnership / IP ownership",
  ],

  // Financial Services
  "banking": [
    "Gross NPA / Net NPA ratio (%)",
    "CASA ratio (%)",
    "Net Interest Margin (NIM %)",
    "Credit cost (%)",
    "Capital Adequacy Ratio (CAR %)",
    "Return on Assets (ROA %)",
    "Return on Equity (ROE %)",
    "Loan book size (₹ cr) & growth",
    "Digital transaction share (%)",
  ],
  "nbfcs-microfinance": [
    "AUM size and growth (%)",
    "Gross NPA (%)",
    "Cost of funds (%)",
    "Average ticket size (₹)",
    "Active borrower base",
    "Collection efficiency (%)",
    "Funding mix (bank loans vs NCD vs securitisation)",
  ],
  "insurance": [
    "Combined ratio (%)",
    "Loss ratio (%)",
    "Expense ratio (%)",
    "Solvency ratio",
    "Gross written premium (₹ cr) & growth",
    "Distribution mix (agent vs bancassurance vs digital)",
    "Market share by line of business",
  ],
  "asset-management-capital-markets": [
    "Assets Under Management (AUM ₹ cr)",
    "Market share (%)",
    "Average expense ratio (%)",
    "Fund performance vs benchmark (alpha)",
    "SIP book size",
    "Retail vs institutional AUM mix",
    "Distribution reach (empanelled distributors)",
  ],
  "fintech-digital-payments": [
    "Gross Merchandise Value / Total Payment Volume (GMV/TPV)",
    "Take rate (bps)",
    "Monthly Active Users (MAU)",
    "Customer Acquisition Cost (CAC)",
    "Revenue per user (ARPU)",
    "Regulatory licenses held",
    "UPI market share (%)",
  ],

  // Technology & Internet
  "it-services-bpm": [
    "Revenue ($ bn) and growth (%)",
    "EBITDA margin (%)",
    "Revenue per employee ($)",
    "Utilisation rate (%)",
    "Deal TCV (Total Contract Value)",
    "Attrition rate (%)",
    "US vs non-US revenue mix",
    "AI/digital revenue share (%)",
  ],
  "saas-software-products": [
    "Annual Recurring Revenue (ARR)",
    "Net Revenue Retention (NRR %)",
    "Customer Acquisition Cost (CAC)",
    "LTV:CAC ratio",
    "Gross churn rate (%)",
    "Gross margin (%)",
    "Rule of 40 score",
  ],
  "ecommerce-quick-commerce": [
    "Gross Merchandise Value (GMV)",
    "Take rate (%)",
    "Contribution margin per order",
    "Dark store / fulfilment centre count",
    "Average order value (AOV)",
    "Customer Acquisition Cost (CAC)",
    "Delivery SLA (minutes/days)",
  ],
  "internet-consumer-tech-platforms": [
    "Monthly / Daily Active Users (MAU/DAU)",
    "ARPU (₹)",
    "DAU:MAU ratio (stickiness)",
    "Monetisation rate (%)",
    "Customer Acquisition Cost (CAC)",
    "Time-on-platform (mins/day)",
    "Ad vs subscription revenue mix",
  ],
  "telecom": [
    "ARPU (₹/month)",
    "Subscriber base (mn)",
    "Spectrum holdings (MHz per band)",
    "Capex/Revenue ratio (%)",
    "Monthly churn rate (%)",
    "5G rollout coverage (%)",
    "Data consumption per user (GB/month)",
    "EBITDA margin (%)",
  ],

  // Healthcare & Pharma
  "pharmaceuticals": [
    "R&D spend as % of revenue",
    "ANDA filings (US generic pipeline)",
    "API vs formulations revenue mix",
    "USFDA / WHO-GMP facility compliance",
    "Domestic vs export revenue split",
    "Branded generics share (%)",
    "Revenue concentration (top product/market %)",
  ],
  "hospitals-healthcare-delivery": [
    "Bed count & occupancy rate (%)",
    "Average Revenue Per Occupied Bed (ARPOB ₹)",
    "Payer mix (self-pay vs insurance vs government)",
    "Average Length of Stay (ALOS days)",
    "EBITDA margin (%)",
    "Owned vs leased vs operated model",
    "Tier-1 vs Tier-2 city mix",
  ],
  "diagnostics-medical-devices": [
    "Tests per day / Revenue per test",
    "Owned lab count and geographic spread",
    "Hub-and-spoke vs franchise model",
    "B2B (hospital referral) vs B2C mix",
    "EBITDA margin (%)",
    "Turnaround time (TAT hours)",
    "Home collection share (%)",
  ],
  "healthtech-digital-health": [
    "Monthly Active Users (MAU)",
    "Patient Acquisition Cost (PAC ₹)",
    "ARPU (₹)",
    "Hospital / insurer partnership count",
    "Regulatory approvals (MDR / CDSCO)",
    "B2C vs B2B2C revenue mix",
    "Retention / repeat visit rate (%)",
  ],

  // Consumer & Retail
  "fmcg": [
    "Revenue and volume growth (%)",
    "Gross margin (%)",
    "A&P spend as % of revenue",
    "Direct distribution reach (towns/outlets)",
    "Market share by category (%)",
    "Premium vs mass product mix",
    "Rural vs urban revenue split",
  ],
  "retail": [
    "Revenue per sq ft (₹)",
    "Same-store sales growth (SSSG %)",
    "Inventory days",
    "Private label share (%)",
    "Store count and pipeline",
    "Omnichannel / online sales share (%)",
    "EBITDA margin (%)",
  ],
  "consumer-durables-electronics": [
    "Market share by category (%)",
    "Revenue growth (%)",
    "Gross margin (%)",
    "Distribution network (dealer count)",
    "After-sales service reach",
    "Import dependency / indigenisation (%)",
    "Premium segment revenue share (%)",
  ],
  "apparel-textiles-footwear": [
    "Revenue and EBITDA margin (%)",
    "Capacity utilisation (%)",
    "Export destination concentration",
    "Value-added vs commodity mix",
    "Brand vs private label revenue",
    "Raw material cost as % of revenue",
    "PLI benefit accrual (₹ cr)",
  ],
  "food-beverage-qsr": [
    "Same-store sales growth (SSSG %)",
    "Average Daily Sales per store (ADS ₹)",
    "Store count and new openings",
    "Payback period per store (years)",
    "Delivery vs dine-in revenue mix",
    "Gross margin (%)",
    "Franchise vs company-owned store split",
  ],

  // Automotive & Industrial Manufacturing
  "automotive-oems": [
    "Domestic market share by segment (%)",
    "EV revenue / volume share (%)",
    "Localisation level (%)",
    "Dealer network size",
    "EBITDA margin (%)",
    "Export volumes and markets",
    "Order backlog (for CV/2W)",
  ],
  "auto-components": [
    "Revenue and EBITDA margin (%)",
    "Customer concentration (top 3 OEM share)",
    "OEM vs aftermarket revenue split",
    "EV-agnostic revenue share (%)",
    "Export share (%)",
    "Capacity utilisation (%)",
    "R&D spend (%)",
  ],
  "electric-vehicles-battery": [
    "Range (km) per charge",
    "Battery cost ($/kWh)",
    "Order book size",
    "FAME / PLI subsidy dependency",
    "Domestic market share by segment (%)",
    "Charging infrastructure / network",
    "Localisation level (%)",
  ],
  "industrial-manufacturing-capital-goods": [
    "Order book / revenue ratio",
    "Revenue growth and EBITDA margin (%)",
    "Export share (%)",
    "Capacity utilisation (%)",
    "Working capital cycle (days)",
    "Government order dependence (%)",
    "R&D / technology capability",
  ],
  "electronics-semiconductors": [
    "PLI benefit accrual (₹ cr)",
    "Import substitution achieved (%)",
    "Domestic vs export revenue mix",
    "Capex (₹ cr) and capacity",
    "Technology node capability",
    "Customer concentration",
    "Value-add level (assembly vs fabrication)",
  ],

  // Infrastructure, Real Estate & Construction
  "real-estate": [
    "Pre-sales value (₹ cr) and units",
    "Collections (₹ cr)",
    "Inventory overhang (months of sales)",
    "Net debt / equity",
    "Launch pipeline (mn sq ft)",
    "Residential vs commercial mix",
    "Geographic concentration (cities)",
  ],
  "construction-engineering-epc": [
    "Order book / revenue ratio",
    "Order inflow growth (%)",
    "EBITDA margin (%)",
    "Working capital cycle (days)",
    "Project concentration (top 3 orders as % of book)",
    "Execution track record (on-time delivery %)",
    "International order share (%)",
  ],
  "cement": [
    "Installed capacity (MTPA) and utilisation (%)",
    "Cost of production (₹/tonne)",
    "EBITDA per tonne (₹)",
    "Freight cost per tonne",
    "Fuel cost exposure (pet coke vs coal)",
    "Regional market share (%)",
    "Capacity expansion pipeline (MTPA)",
  ],
  "roads-highways-urban-infrastructure": [
    "Order book / revenue ratio",
    "HAM vs BOT vs EPC project mix",
    "Toll collection (₹ cr/km)",
    "Equity IRR on BOT projects (%)",
    "Collection efficiency (%)",
    "NHAI award pipeline exposure",
    "Net debt / equity",
  ],
  "ports-airports-logistics-infrastructure": [
    "Cargo throughput (MTPA / mn pax)",
    "EBITDA per tonne / per passenger (₹)",
    "Capacity utilisation (%)",
    "Concession tenure remaining (years)",
    "Hinterland connectivity",
    "Commodity concentration",
    "Capex pipeline (₹ cr)",
  ],

  // Metals, Mining & Chemicals
  "steel": [
    "Crude steel capacity (MTPA) and utilisation (%)",
    "Cost of production (₹/tonne)",
    "EBITDA per tonne (₹)",
    "Flat vs long product mix",
    "Coking coal sourcing (captive vs spot)",
    "Export share (%)",
    "Debt / EBITDA ratio",
  ],
  "non-ferrous-metals": [
    "Production volume (MT) and growth",
    "LME price realisation and hedging policy",
    "Cost quartile position globally",
    "Integration level (mining → smelting → downstream)",
    "Captive mining share (%)",
    "Export mix and geography",
    "EBITDA margin (%)",
  ],
  "mining-coal": [
    "Production volume (MT) and growth (%)",
    "E-auction premium over notified price",
    "Cost of production per tonne (₹)",
    "Mine life (years)",
    "CIL-linked vs captive mine revenue",
    "Washery / value-add capacity",
    "Environmental / regulatory risk",
  ],
  "chemicals-petrochemicals": [
    "Revenue and EBITDA margin (%)",
    "Value-added specialty vs commodity mix",
    "Feedstock integration level",
    "Export share and geographies",
    "Capacity utilisation (%)",
    "Feedstock cost volatility exposure",
    "R&D pipeline",
  ],
  "specialty-chemicals-agrochemicals": [
    "Revenue growth and gross margin (%)",
    "R&D spend as % of revenue",
    "CRAMS / CDMO revenue share (%)",
    "China+1 opportunity exposure",
    "Customer concentration (top 3 clients %)",
    "Export vs domestic revenue mix",
    "Regulatory approvals (EPA, EC)",
  ],

  // Agriculture & Allied
  "agriculture-farm-inputs": [
    "Market share by crop segment (%)",
    "Direct reach (districts / retail touchpoints)",
    "Product mix (seeds vs pesticides vs nutrients)",
    "R&D pipeline (new varieties / molecules)",
    "Revenue growth and EBITDA margin (%)",
    "Monsoon / seasonal revenue dependency",
  ],
  "agritech": [
    "Registered farmer base",
    "GMV / transaction value (₹ cr)",
    "Take rate (%)",
    "FPO / cooperative partnerships",
    "Geographic coverage (districts/states)",
    "B2B vs B2C revenue mix",
    "Burn rate and unit economics",
  ],
  "food-processing": [
    "Revenue and EBITDA margin (%)",
    "Value-add level (raw → processed → branded)",
    "Private label vs branded revenue mix",
    "Export share and key geographies",
    "Capacity utilisation (%)",
    "Raw material sourcing strategy",
    "Regulatory certifications (FSSAI, USFDA)",
  ],
  "fertilizers": [
    "Capacity (MTPA) — urea vs complex",
    "Subsidy receivable and working capital impact",
    "Gas sourcing cost ($/mmBtu)",
    "Urea vs non-urea product mix",
    "Cost of production vs MRP",
    "Distribution reach",
    "Capex / capacity expansion pipeline",
  ],
  "dairy-animal-husbandry": [
    "Milk procurement (Lakh Litres Per Day — LLPD)",
    "Value-added products (VAP) share of revenue (%)",
    "EBITDA margin (%)",
    "Farmer / procurement network (villages)",
    "Geographic reach (states)",
    "Brand vs commodity revenue mix",
    "Cold chain infrastructure (chilling centres)",
  ],

  // Transportation & Logistics
  "aviation": [
    "Revenue per Available Seat Km (RASK) vs Cost per ASK (CASK)",
    "Passenger Load Factor (PLF %)",
    "Fleet size and average age (years)",
    "Domestic vs international market share (%)",
    "On-time performance (%)",
    "Fuel cost as % of operating cost",
    "Net debt / equity",
  ],
  "railways": [
    "Freight volume (NTTKM — Net Tonne Tonne Km)",
    "Commodity mix (coal, container, bulk)",
    "Revenue per tonne-km (₹)",
    "DFC (Dedicated Freight Corridor) exposure",
    "Wagons per day / turnaround time",
    "Capex / modernisation plan",
  ],
  "shipping-ports": [
    "Fleet DWT (Deadweight Tonnage)",
    "Vessel utilisation rate (%)",
    "Average time-charter equivalent (TCE) day rate ($)",
    "Time charter vs spot revenue mix",
    "Route / trade lane concentration",
    "Fleet age and scrapping exposure",
  ],
  "road-logistics-3pl": [
    "Fleet size and utilisation (%)",
    "Revenue per truck per day (₹)",
    "FTL vs LTL vs express mix",
    "Geographic coverage (pin codes / branches)",
    "EBITDA margin (%)",
    "Tech platform capability (TMS/WMS)",
    "Customer concentration (top 5 clients %)",
  ],
  "warehousing-supply-chain-tech": [
    "Sq ft under management (mn sq ft)",
    "Average rental yield (₹/sq ft/month)",
    "Occupancy rate (%)",
    "Grade A vs Grade B warehouse mix",
    "E-commerce client share of revenue (%)",
    "Geographic spread (cities / parks)",
    "EBITDA margin (%)",
  ],

  // Media, Entertainment & Gaming
  "television-film": [
    "Viewership share / GRP",
    "Subscription revenue share (%)",
    "Content cost per hour produced (₹ cr)",
    "Ad revenue growth (%)",
    "OTT transition progress (streaming subs)",
    "Hindi GEC market share (%)",
  ],
  "digital-media-ott": [
    "Monthly Active Users (MAU) / Paid subscribers",
    "ARPU (₹/month)",
    "Content spend (₹ cr/year)",
    "Monthly churn rate (%)",
    "Ad vs subscription revenue mix",
    "India vs international revenue mix",
    "Originals output (titles per year)",
  ],
  "gaming-esports": [
    "Daily Active Users (DAU)",
    "ARPU (₹)",
    "Pay-to-play conversion rate (%)",
    "Genre concentration",
    "India vs export revenue mix",
    "Tournament/esports prize pool (₹ cr)",
    "User retention (D7 / D30 %)",
  ],
  "advertising-adtech": [
    "Market share (%)",
    "Digital vs traditional revenue mix",
    "Programmatic / automated buying share (%)",
    "Client retention rate (%)",
    "Revenue per campaign (₹)",
    "Data / audience segment quality",
    "EBITDA margin (%)",
  ],

  // Education & Skilling
  "k12-education": [
    "Student enrolment",
    "Annual fee per student (₹)",
    "Teacher:student ratio",
    "Board exam performance / pass rate (%)",
    "School / centre count and pipeline",
    "Owned vs franchised school mix",
    "EBITDA margin (%)",
  ],
  "higher-education": [
    "Total student enrolment",
    "Annual fee per student (₹)",
    "NAAC / NBA accreditation grade",
    "Campus placement rate (%) and median salary",
    "Faculty:student ratio and PhD-qualified %",
    "Research output (publications / patents)",
    "Seats and expansion pipeline",
  ],
  "edtech": [
    "Monthly Active Users (MAU)",
    "Paid conversion rate (%)",
    "ARPU (₹)",
    "Course completion rate (%)",
    "B2C vs B2B (school/enterprise) revenue mix",
    "Customer Acquisition Cost (CAC ₹)",
    "Monthly burn rate and runway",
  ],
  "vocational-training-skilling": [
    "Annual training capacity (seats)",
    "Placement rate after training (%)",
    "Industry / employer partnership count",
    "Government scheme revenue share (PMKVY etc.) (%)",
    "Course portfolio breadth (trades / sectors)",
    "Certification recognition (NSDC / sector skills council)",
    "EBITDA margin (%)",
  ],

  // Hospitality & Travel
  "hotels-resorts": [
    "Revenue Per Available Room (RevPAR ₹)",
    "Average Daily Rate (ADR ₹)",
    "Occupancy rate (%)",
    "Owned vs managed vs franchised property mix",
    "Brand tier spread (luxury vs midscale vs budget)",
    "EBITDA margin (%)",
    "Rooms pipeline (under development)",
  ],
  "travel-tourism-otas": [
    "Gross Merchandise Value (GMV ₹ cr)",
    "Take rate (%)",
    "Hotels vs flights vs holidays revenue mix",
    "Mobile booking share (%)",
    "Loyalty program member base",
    "Customer Acquisition Cost (CAC ₹)",
    "Repeat booking rate (%)",
  ],

  // Public Sector, Government & Defense
  "defense-aerospace": [
    "Order book / revenue ratio",
    "Export order share (%)",
    "Indigenisation / Make in India level (%)",
    "Technology category (platforms vs components vs MRO)",
    "Government vs commercial revenue mix",
    "R&D spend (%)",
    "Capex and programme execution track record",
  ],
  "government-psu-enterprises": [
    "Return on Equity vs cost of equity",
    "Dividend payout ratio (%)",
    "Capex / revenue ratio",
    "Market share in regulated sector (%)",
    "Subsidy / government support dependence",
    "Asset monetisation progress",
    "Net debt / EBITDA",
  ],
  "space-satellite": [
    "Launch vehicle success rate (%)",
    "Satellite manufacturing backlog",
    "Commercial revenue share (%)",
    "Technology tier (PSLV vs GSLV vs LVM3)",
    "Foreign customer / export order share",
    "Capex and programme timeline",
    "Private sector partnership model",
  ],
};
