import { ChevronRightIcon, FolderIcon, FolderOpenIcon } from "lucide-react";
import { DriveFileLink } from "@/components/drive-file-link";
import type { DriveFileEntry, DriveFileGroup } from "@/lib/drive-sync/client";

export interface DriveFileData {
  tags: string[];
  summary: string | null;
}

interface FolderNode {
  name: string;
  files: DriveFileEntry[];
  children: Map<string, FolderNode>;
}

function buildTree(groups: DriveFileGroup[]): FolderNode {
  const root: FolderNode = { name: "", files: [], children: new Map() };

  for (const group of groups) {
    if (!group.folderName) {
      root.files.push(...group.files);
      continue;
    }

    let node = root;
    for (const segment of group.folderName.split("/")) {
      let child = node.children.get(segment);
      if (!child) {
        child = { name: segment, files: [], children: new Map() };
        node.children.set(segment, child);
      }
      node = child;
    }
    node.files.push(...group.files);
  }

  return root;
}

function sortedFiles(files: DriveFileEntry[]): DriveFileEntry[] {
  return [...files].sort((a, b) => a.name.localeCompare(b.name));
}

function sortedChildren(node: FolderNode): FolderNode[] {
  return [...node.children.values()].sort((a, b) => a.name.localeCompare(b.name));
}

function countFilesDeep(node: FolderNode): number {
  let count = node.files.length;
  for (const child of node.children.values()) count += countFilesDeep(child);
  return count;
}

// Indentation is depth-based padding only, not stacked border lines — nesting
// several folders deep with each level adding its own border looks busy and
// cramped. A single consistent step per level reads cleaner at any depth.
const INDENT_STEP_PX = 20;

function FolderSection({
  node,
  subject,
  fileDataMap,
  depth,
}: {
  node: FolderNode;
  subject: string;
  fileDataMap: Map<string, DriveFileData>;
  depth: number;
}) {
  return (
    <details className="group/folder">
      <summary
        style={{ paddingLeft: depth * INDENT_STEP_PX }}
        className="flex cursor-pointer list-none items-center gap-2 rounded-md py-2 pr-2 text-sm font-medium text-foreground hover:bg-accent [&::-webkit-details-marker]:hidden"
      >
        <ChevronRightIcon className="size-3.5 shrink-0 text-muted-foreground transition-transform group-open/folder:rotate-90" />
        <FolderIcon className="size-4 shrink-0 text-muted-foreground group-open/folder:hidden" />
        <FolderOpenIcon className="hidden size-4 shrink-0 text-muted-foreground group-open/folder:block" />
        <span className="truncate">{node.name}</span>
        <span className="rounded-full bg-muted px-1.5 py-0.5 text-xs font-normal text-muted-foreground">
          {countFilesDeep(node)}
        </span>
      </summary>
      <div className="flex flex-col gap-0.5">
        {sortedFiles(node.files).map((file) => (
          <DriveFileLink
            key={file.id}
            file={file}
            subject={subject}
            tags={fileDataMap.get(file.id)?.tags ?? []}
            initialSummary={fileDataMap.get(file.id)?.summary ?? null}
            indentPx={(depth + 1) * INDENT_STEP_PX}
          />
        ))}
        {sortedChildren(node).map((child) => (
          <FolderSection key={child.name} node={child} subject={subject} fileDataMap={fileDataMap} depth={depth + 1} />
        ))}
      </div>
    </details>
  );
}

export function SubjectDriveFiles({
  groups,
  subject,
  fileDataMap,
}: {
  groups: DriveFileGroup[] | null;
  subject: string;
  fileDataMap: Map<string, DriveFileData>;
}) {
  if (!groups || groups.every((g) => g.files.length === 0)) return null;

  const tree = buildTree(groups);

  return (
    <div className="overflow-hidden rounded-lg border border-border bg-card">
      <div className="flex items-center gap-2 border-b border-border px-4 py-3">
        <FolderIcon className="size-4 text-muted-foreground" />
        <div>
          <h2 className="text-sm font-semibold text-foreground">Files in Drive</h2>
          <p className="text-xs text-muted-foreground">Opens in Google Drive. Tags and summaries generated by AI.</p>
        </div>
      </div>
      <div className="flex flex-col gap-0.5 p-2">
        {sortedFiles(tree.files).map((file) => (
          <DriveFileLink
            key={file.id}
            file={file}
            subject={subject}
            tags={fileDataMap.get(file.id)?.tags ?? []}
            initialSummary={fileDataMap.get(file.id)?.summary ?? null}
            indentPx={0}
          />
        ))}
        {sortedChildren(tree).map((child) => (
          <FolderSection key={child.name} node={child} subject={subject} fileDataMap={fileDataMap} depth={0} />
        ))}
      </div>
    </div>
  );
}
