import { ExternalLinkIcon, FileTextIcon } from "lucide-react";
import type { DriveFileEntry, DriveFileGroup } from "@/lib/drive-sync/client";

function TagChip({ tag }: { tag: string }) {
  return (
    <span className="inline-flex items-center rounded-full bg-neutral-100 px-2 py-0.5 text-xs text-neutral-500">
      {tag}
    </span>
  );
}

function FileLink({
  file,
  tags,
}: {
  file: DriveFileEntry;
  tags: string[];
}) {
  return (
    <a
      href={file.webViewLink}
      target="_blank"
      rel="noopener noreferrer"
      className="group flex flex-col gap-1 rounded-md px-2 py-2 transition-colors hover:bg-neutral-50"
    >
      <div className="flex items-center gap-2">
        <FileTextIcon className="size-4 shrink-0 text-neutral-400" />
        <span className="truncate text-sm text-neutral-600 group-hover:text-neutral-900 group-hover:underline">
          {file.name}
        </span>
        <ExternalLinkIcon className="ml-auto size-3.5 shrink-0 text-neutral-300 group-hover:text-neutral-400" />
      </div>
      {tags.length > 0 && (
        <div className="flex flex-wrap gap-1 pl-6">
          {tags.map((tag) => (
            <TagChip key={tag} tag={tag} />
          ))}
        </div>
      )}
    </a>
  );
}

function FileGroup({
  group,
  tagMap,
}: {
  group: DriveFileGroup;
  tagMap: Map<string, string[]>;
}) {
  return (
    <div className="flex flex-col">
      {group.folderName ? (
        <h3 className="px-2 pb-1 text-xs font-medium uppercase tracking-wide text-neutral-400">
          {group.folderName}
        </h3>
      ) : null}
      <div className="flex flex-col">
        {group.files.map((file) => (
          <FileLink key={file.id} file={file} tags={tagMap.get(file.id) ?? []} />
        ))}
      </div>
    </div>
  );
}

export function SubjectDriveFiles({
  groups,
  tagMap,
}: {
  groups: DriveFileGroup[] | null;
  tagMap: Map<string, string[]>;
}) {
  if (!groups || groups.every((g) => g.files.length === 0)) return null;

  return (
    <div className="rounded-lg border border-neutral-200 bg-white p-4">
      <h2 className="px-2 text-sm font-semibold text-neutral-900">Files in Drive</h2>
      <p className="px-2 pb-2 text-xs text-neutral-500">Opens in Google Drive. Tags generated by AI.</p>
      <div className="flex flex-col gap-3">
        {groups.map((group) => (
          <FileGroup key={group.folderName ?? "_root"} group={group} tagMap={tagMap} />
        ))}
      </div>
    </div>
  );
}
