import { ChevronRightIcon, ExternalLinkIcon, FileTextIcon, FolderIcon } from "lucide-react";
import type { DriveFileEntry, DriveFileGroup } from "@/lib/drive-sync/client";

function TagChip({ tag }: { tag: string }) {
  return (
    <span className="inline-flex items-center rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">
      {tag}
    </span>
  );
}

function FileLink({
  file,
  tags,
}: {
  file: DriveFileEntry;
  tags: string[];
}) {
  return (
    <a
      href={file.webViewLink}
      target="_blank"
      rel="noopener noreferrer"
      className="group flex flex-col gap-1 rounded-md px-2 py-2 transition-colors hover:bg-accent"
    >
      <div className="flex items-center gap-2">
        <FileTextIcon className="size-4 shrink-0 text-muted-foreground" />
        <span className="truncate text-sm text-muted-foreground group-hover:text-foreground group-hover:underline">
          {file.name}
        </span>
        <ExternalLinkIcon className="ml-auto size-3.5 shrink-0 text-muted-foreground/50 group-hover:text-muted-foreground" />
      </div>
      {tags.length > 0 && (
        <div className="flex flex-wrap gap-1 pl-6">
          {tags.map((tag) => (
            <TagChip key={tag} tag={tag} />
          ))}
        </div>
      )}
    </a>
  );
}

interface FolderNode {
  name: string;
  files: DriveFileEntry[];
  children: Map<string, FolderNode>;
}

function buildTree(groups: DriveFileGroup[]): FolderNode {
  const root: FolderNode = { name: "", files: [], children: new Map() };

  for (const group of groups) {
    if (!group.folderName) {
      root.files.push(...group.files);
      continue;
    }

    let node = root;
    for (const segment of group.folderName.split("/")) {
      let child = node.children.get(segment);
      if (!child) {
        child = { name: segment, files: [], children: new Map() };
        node.children.set(segment, child);
      }
      node = child;
    }
    node.files.push(...group.files);
  }

  return root;
}

function FolderSection({
  node,
  tagMap,
}: {
  node: FolderNode;
  tagMap: Map<string, string[]>;
}) {
  return (
    <details open className="group/folder">
      <summary className="flex cursor-pointer list-none items-center gap-2 rounded-md px-2 py-1.5 text-sm font-medium text-foreground hover:bg-accent [&::-webkit-details-marker]:hidden">
        <ChevronRightIcon className="size-3.5 shrink-0 text-muted-foreground transition-transform group-open/folder:rotate-90" />
        <FolderIcon className="size-4 shrink-0 text-muted-foreground" />
        {node.name}
      </summary>
      <div className="flex flex-col gap-1 border-l border-border pl-4 ml-3.5">
        {node.files.map((file) => (
          <FileLink key={file.id} file={file} tags={tagMap.get(file.id) ?? []} />
        ))}
        {[...node.children.values()].map((child) => (
          <FolderSection key={child.name} node={child} tagMap={tagMap} />
        ))}
      </div>
    </details>
  );
}

export function SubjectDriveFiles({
  groups,
  tagMap,
}: {
  groups: DriveFileGroup[] | null;
  tagMap: Map<string, string[]>;
}) {
  if (!groups || groups.every((g) => g.files.length === 0)) return null;

  const tree = buildTree(groups);

  return (
    <div className="rounded-lg border border-border bg-card p-4">
      <h2 className="px-2 text-sm font-semibold text-foreground">Files in Drive</h2>
      <p className="px-2 pb-2 text-xs text-muted-foreground">Opens in Google Drive. Tags generated by AI.</p>
      <div className="flex flex-col gap-1">
        {tree.files.map((file) => (
          <FileLink key={file.id} file={file} tags={tagMap.get(file.id) ?? []} />
        ))}
        {[...tree.children.values()].map((child) => (
          <FolderSection key={child.name} node={child} tagMap={tagMap} />
        ))}
      </div>
    </div>
  );
}
